### ISSUE TITLE
Yam update seems to add numbers to Config.yml

### ISSUE THREAD

**Issue by mylesthedev** [PlatoCreative/plato-silverstripe-installer#1]
When the script updates the Yaml file it seems to replace "-" with 0 or 1. 
e.g.

```

---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'

---
```

Becomes:

```

---
Name: mysite
After:
  0: 'framework/*'
  1: 'cms/*'

---
```

Everything still works as it should but it's not ideal having it like that.

**Comment by gorriecoe** [comment]
This is pretty standard behaviour and happens not just in yaml files.  Its caused by array indexing.

**Comment by mylesthedev** [comment]
Sweet, I wasn't sure back then if it affected anything. I guess it's more visually annoying more than anything.
